on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:2.4
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export
      - name: West Build (Amalgamate Left)
        run: west build -s zmk/app -b amalgamate_left -- -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Amalgamate DTS File
        if: ${{ always() }}
        run: cat -n build/zephyr/amalgamate_left.dts.pre.tmp
      - name: Amalgamate Left Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 amalgamate_left.uf2
      - name: Archive (Amalgamate Left)
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: amalgamate_left.uf2
      - name: West Build (Amalgamate Right)
        run: west build --pristine -s zmk/app -b amalgamate_right -- -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: Amalgamate Right Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 amalgamate_right.uf2
      - name: Archive (Amalgamate Right)
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: amalgamate_right.uf2
